name: Terraform Apply

on:
  workflow_dispatch: # Manually triggered
    inputs:
      email:
        description: 'Email address for notification'
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Send Email Notification
        run: echo "Deployment Completed" | mail -s "Terraform Deployment" ${{ github.event.inputs.email }}
        env:
          SMTP_SERVER: smtp.yourdomain.com
          SMTP_PORT: 587
          SMTP_USERNAME: username
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
